# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo $ANDROID_HOME

# - task: Npm@1
#   inputs:
#     command: 'custom'
#     customCommand: 'install'

# - task: Npm@1
#   inputs:
#     command: 'custom'
#     customCommand: 'install @ionic/cli'

# - task: Npm@1
#   inputs:
#     command: 'custom'
#     customCommand: 'install cordova'

# - task: Npm@1
#   inputs:
#     command: 'custom'
#     customCommand: 'run setup'

# - task: Npm@1
#   inputs:
#     command: 'custom'
#     customCommand: 'run build'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'

