# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:


- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install @ionic/cli'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install cordova'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run remove'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run setup'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/platforms/android/app/build/outputs/apk/debug'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

